version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get install nodejs -y
      - gem install bundler
  pre_build:
    commands:
      - cd src
      - bundle install
      - npm install
  build:
    commands:
      - NO_CONTRACTS=true bundle exec middleman build
  post_build:
    commands:
        - aws s3 sync build/ s3://$S3_BUCKET --delete
        - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
