AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Creates static web page with a Cloudfront CDN, domain aliases, custom SSL certificate, and CI pipeline.

Parameters:
  AcmCertificateArn:
    AllowedPattern: "arn:aws:acm:.*"
    Default: arn:aws:acm:us-east-1:295005258746:certificate/2f702844-d6e5-4573-8a41-57fcc0c1992b
    Description: The AWS Certificate Manager certificate ARN associated with your top-level domain and www subdomain
    Type: String
  Route53HostZoneName:
    Default: tklon.com
    Description: The Route 53 hosted zone name where DNS records will be created
    Type: String
  GitHubRepositoryOwner:
    Type: String
    Default: teeeg
  GitHubRepositoryName:
    Type: String
    Default: tklon.com

Resources:
  WebsiteStaticAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Route53HostZoneName}-assets
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  WebsiteStaticAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteStaticAssetsBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudfrontOriginAccessIdentity.S3CanonicalUserId
            Resource: !Sub "${WebsiteStaticAssetsBucket.Arn}/*"

  CloudfrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "CloudFront OAI for ${Route53HostZoneName}"

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref Route53HostZoneName
          - !Sub www.${Route53HostZoneName}
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: "/404.html"
            ResponseCode: 404
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName: !GetAtt WebsiteStaticAssetsBucket.DomainName
            Id: !Ref WebsiteStaticAssetsBucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudfrontOriginAccessIdentity}"
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: true
          TargetOriginId: !Ref WebsiteStaticAssetsBucket
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt PathRewriteFunction.FunctionMetadata.FunctionARN
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  PathRewriteFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "${AWS::StackName}-path-rewrite"
      AutoPublish: true
      FunctionConfig:
        Comment: Append index.html to directory-style request URIs
        Runtime: cloudfront-js-2.0
      FunctionCode: |
        function handler(event) {
          var request = event.request;
          request.uri = request.uri.replace(/\/$/, '/index.html');
          return request;
        }

  DNSAliasNames:
    Type: AWS::Route53::RecordSetGroup
    Description: Alias names must match cloudfront aliases, see "CloudfrontDistribution:DistributionConfig:Aliases"
    DependsOn:
      - CloudfrontDistribution
    Properties:
      HostedZoneName: !Sub "${Route53HostZoneName}."
      RecordSets:
        - Name: !Sub "www.${Route53HostZoneName}"
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt CloudfrontDistribution.DomainName
        - Name: !Ref Route53HostZoneName
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt CloudfrontDistribution.DomainName
        - Name: !Sub "www.${Route53HostZoneName}"
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt CloudfrontDistribution.DomainName
        - Name: !Ref Route53HostZoneName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt CloudfrontDistribution.DomainName

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: BuildDeployAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource: !GetAtt WebsiteStaticAssetsBucket.Arn
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub "${WebsiteStaticAssetsBucket.Arn}/*"
              - Effect: Allow
                Action: cloudfront:CreateInvalidation
                Resource: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudfrontDistribution}"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Resource:
                  - !GetAtt BuildPipelineBucket.Arn
                  - !Sub "${BuildPipelineBucket.Arn}/*"

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: CodepipelineBucketAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:GetBucketVersioning
                Resource:
                  - !GetAtt BuildPipelineBucket.Arn
                  - !Sub "${BuildPipelineBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource: !GetAtt BuildDeployBuildTask.Arn
              - Effect: Allow
                Action: codestar-connections:UseConnection
                Resource: !Ref GitHubConnection

  GitHubConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: !Sub "${AWS::StackName}-github"
      ProviderType: GitHub

  BuildPipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BuildDeployPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref BuildPipelineBucket
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              InputArtifacts: []
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              OutputArtifacts:
                - Name: SourceCode
              RunOrder: 1
              Configuration:
                ConnectionArn: !Ref GitHubConnection
                FullRepositoryId: !Sub "${GitHubRepositoryOwner}/${GitHubRepositoryName}"
                BranchName: master
                OutputArtifactFormat: CODE_ZIP
        - Name: BuildDeploy
          Actions:
            - Name: BuildDeploy
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref BuildDeployBuildTask
              InputArtifacts:
                - Name: SourceCode
              RunOrder: 1

  BuildDeployBuildTask:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:8.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: S3_BUCKET
            Value: !Ref WebsiteStaticAssetsBucket
            Type: PLAINTEXT
          - Name: CLOUDFRONT_DISTRIBUTION_ID
            Value: !Ref CloudfrontDistribution
            Type: PLAINTEXT
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: ./deploy/buildspec.yml
